apiVersion: v1
kind: Service
metadata:
  name: prd3
  namespace: alpha
  labels:
    app: prd3
    team: alpha
spec:
  type: ClusterIP
  selector:
    app: prd3
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
