apiVersion: v1
kind: Service
metadata:
  name: uat
  namespace: alpha
  labels:
    app: uat
    team: alpha
spec:
  type: ClusterIP
  selector:
    app: uat
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
