apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: alpha
  labels:
    app: demoapp
    team: alpha
spec:
  type: ClusterIP
  selector:
    app: demoapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
