helm upgrade --install argocd port-labs/port-ocean \
	--set port.clientId="ID6jVlKlbM6l1CLaVQuvIq9lIUCy8WFN"  \
	--set port.clientSecret="HXUv7DAgA58msW6CgLXgPCxJYIIIS90MLsjaXYns2WzyztgYf7yKPkjeIyBPNFmf"  \
	--set port.baseUrl="https://api.port.io"  \
	--set initializePortResources=true  \
	--set sendRawDataExamples=true  \
	--set scheduledResyncInterval=360  \
	--set integration.identifier="argocd"  \
	--set integration.type="argocd"  \
	--set integration.eventListener.type="POLLING"  \
	--set integration.secrets.token="Enter value here"  \
	--set integration.config.serverUrl="Enter value here" 