apiVersion: v1
kind: Service
metadata:
  name: {{appName}}
  namespace: {{team}}
  labels:
    app: {{appName}}
    team: {{team}}
spec:
  type: ClusterIP
  selector:
    app: {{appName}}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
